const germanAdjective = [
    {
        German:"aalglatt",
        English:"slippery",
        ID:1
    },
    {German:"abenteuerlich",English:"adventurous",ID:2},
    {German:"abhaengig",English:"dependent",ID:3},
    {German:"aggressiv",English:"aggressive",ID:4},
    {German:"aehnlich",English:"similar",ID:5},
    {German:"ahnungslos",English:"clueless",ID:6},
    {German:"aktiv",English:"active",ID:7},
    {German:"allein",English:"alone",ID:8},
    {German:"alt",English:"old",ID:9},
    {German:"anpassungsfaehig",English:"adaptable",ID:10},
    {German:"anstaendig",English:"decent",ID:11},
    {German:"aergerlich",English:"annoying",ID:12},
    {German:"arm",English:"poor",ID:13},
    {German:"art",English:"kind",ID:14},
    {German:"attraktiv",English:"attractive",ID:15},
    {German:"aufgeklaert",English:"enlightened",ID:16},
    {German:"aufgeregt",English:"excited, upset, nervous",ID:17},
    {German:"aufgeschlossen",English:"open-minded",ID:18},
    {German:"aufrichtig",English:"sincere, genuine, candid",ID:19},
    {German:"blass",English:"pale",ID:20},
    {German:"begabt",English:"gifted, talented",ID:21},
    {German:"begeistert",English:"excited, enthusiastic, thrilled",ID:22},
    {German:"beruehmt",English:"famous",ID:23},
    {German:"beliebt, populaer",English:"popular",ID:24},
    {German:"bestimmt",English:"special, certain",ID:25},
    {German:"besser",English:"better",ID:26},
    {German:"bequem",English:"comfortable",ID:27},
    {German:"bescheiden",English:"modest, humble",ID:28},
    {German:"beste",English:"best",ID:29},
    {German:"bezaubernd",English:"enchanting, fascinating",ID:30},
    {German:"billig",English:"cheap, inexpensive",ID:31},
    {German:"bloed",English:"stupid, ignorant",ID:32},
    {German:"blondine",English:"blond",ID:33},
    {German:"boshaft",English:"malicious, mean",ID:34},
    {German:"brav",English:"well-behaved, good",ID:35},
    {German:"charmant",English:"charming",ID:36},
    {German:"dankbar",English:"grateful, thankful",ID:37},
    {German:"dick",English:"thick",ID:38},
    {German:"direkt",English:"direct, straight",ID:39},
    {German:"doof, dumm",English:"stupid, dumb",ID:40},
    {German:"dunkel",English:"dark",ID:41},
    {German:"duenn",English:"thin",ID:42},
    {German:"ehrgeizig",English:"ambitious",ID:43},
    {German:"ehrlich",English:"honest",ID:44},
    {German:"eifersuechtig",English:"jealous",ID:45},
    {German:"einfach",English:"simple, plain, easy",ID:46},
    {German:"eingebildet",English:"conceited, vain",ID:47},
    {German:"einmalig",English:"unique",ID:48},
    {German:"einsam",English:"lonely",ID:49},
    {German:"ekelhaft",English:"nasty, detestable",ID:50},
    {German:"eklig",English:"disgusting, gross",ID:51},
    {German:"empfindlich",English:"sensitive",ID:52},
    {German:"eng",English:"narrow, close",ID:53},
    {German:"engagiert",English:"dedicated, committed",ID:54},
    {German:"engstirnig",English:"narrow-minded",ID:55},
    {German:"entscheidend",English:"decisive",ID:56},
    {German:"entspannend",English:"laidback",ID:57},
    {German:"erfolgreich",English:"successful",ID:58},
    {German:"ernst",English:"serious",ID:59},
    {German:"erste",English:"first",ID:60},
    {German:"erstklassig",English:"first-class, high-quality, topnotch",ID:61},
    {German:"falsch",English:"wrong, false",ID:62},
    {German:"fantastisch",English:"fantastic",ID:63},
    {German:"faszinierend",English:"fascinating",ID:64},
    {German:"faul",English:"lazy",ID:65},
    {German:"feig",English:"cowardly",ID:66},
    {German:"fein",English:"fine",ID:67},
    {German:"fest",English:"solid, strong, firm",ID:68},
    {German:"fett",English:"fat",ID:69},
    {German:"feigling",English:"coward",ID:70},
    {German:"fleißig",English:"diligent, hard-working, industrious",ID:71},
    {German:"fortgeschritten",English:"advanced",ID:72},
    {German:"frech",English:"naughty, cheeky, sassy",ID:73},
    {German:"frei",English:"free",ID:74},
    {German:"fremd",English:"foreign, strange",ID:75},
    {German:"freundlich",English:"friendly, kind",ID:76},
    {German:"froh",English:"happy",ID:77},
    {German:"froehlich",English:"cheerful",ID:78},
    {German:"fromm",English:"pious",ID:79},
    {German:"frueh",English:"early",ID:80},
    {German:"ganz",English:"whole",ID:81},
    {German:"gastfreundlich",English:"hospitable",ID:82},
    {German:"gebildet",English:"educated, cultured",ID:83},
    {German:"geduldig",English:"patient",ID:84},
    {German:"gefaehrlich",English:"dangerous",ID:85},
    {German:"gefuehlvoll",English:"sensitive, emotional",ID:86},
    {German:"geistreich",English:"witty, brilliant",ID:87},
    {German:"geizig",English:"stingy, cheap",ID:88},
    {German:"gemein",English:"low, rude, vulgar",ID:89},
    {German:"gemeinsam",English:"common, mutual",ID:90},
    {German:"gemuetlich",English:"pleasant, cozy",ID:91},
    {German:"genial",English:"ingenious, brilliant",ID:92},
    {German:"gerecht",English:"just, righteous",ID:93},
    {German:"geschaetzt",English:"dear, valued",ID:94},
    {German:"gescheit",English:"clever, bright",ID:95},
    {German:"geschickt",English:"skillful",ID:96},
    {German:"geschwaetzig",English:"talkative, chatty",ID:97},
    {German:"gesellig",English:"sociable, friendly",ID:98},
    {German:"gesund",English:"healthy",ID:99},
    {German:"gierig",English:"greedy",ID:100},
    {German:"glaubwuerdig",English:"credible, believable",ID:101},
    {German:"gleich",English:"same, right away, just",ID:102},
    {German:"gleichzeitig",English:"simultaneous",ID:103},
    {German:"gluecklich",English:"happy, lucky, blessed",ID:104},
    {German:"grausam",English:"cruel",ID:105},
    {German:"grob",English:"coarse, uncouth, rude",ID:106},
    {German:"großzuegig",English:"generous",ID:107},
    {German:"groß",English:"big, large, tall",ID:108},
    {German:"gruen",English:"green",ID:109},
    {German:"gut",English:"good, well",ID:110},
    {German:"gut angezogen",English:"well-dressed",ID:111},
    {German:"gut gelaunt",English:"cheerful, in a good mood",ID:112},
    {German:"halb",English:"half",ID:113},
    {German:"halsstarrig",English:"stubborn",ID:114},
    {German:"hart",English:"hard, tough",ID:115},
    {German:"hartnaeckig",English:"hard-headed, stubborn",ID:116},
    {German:"haesslich",English:"ugly",ID:117},
    {German:"haeufig",English:"frequent",ID:118},
    {German:"heiß",English:"hot",ID:119},
    {German:"heiter",English:"cheerful",ID:120},
    {German:"hell",English:"bright, vivid",ID:121},
    {German:"hemmungslos",English:"uninhibited, unrestrained",ID:122},
    {German:"herrlich",English:"wonderful, magnificent, marvelous",ID:123},
    {German:"herzlos",English:"heartless, unfeeling",ID:124},
    {German:"hilfreich",English:"helpful",ID:125},
    {German:"hinterlistig",English:"deceitful, treacherous",ID:126},
    {German:"hoch",English:"high",ID:127},
    {German:"hochmuetig",English:"haughty, proud",ID:128},
    {German:"hochnaesig",English:"snooty, stuck up",ID:129},
    {German:"hoeflich",English:"polite",ID:130},
    {German:"huebsch",English:"pretty, handsome",ID:131},
    {German:"hundemuede",English:"dog-tired",ID:132},
    {German:"hungrig",English:"hungry",ID:133},
    {German:"idealistisch",English:"idealistic",ID:134},
    {German:"intelligent",English:"intelligent",ID:135},
    {German:"interessant",English:"interesting",ID:136},
    {German:"intolerant",English:"intolerant",ID:137},
    {German:"jung",English:"young",ID:138},
    {German:"kalt",English:"cold, unfriendly",ID:139},
    {German:"kindisch",English:"childish",ID:140},
    {German:"kindlich",English:"childlike",ID:141},
    {German:"klar",English:"clear",ID:142},
    {German:"klasse, toll, super",English:"great, super",ID:143},
    {German:"klein",English:"small, little, short",ID:144},
    {German:"kleinlich",English:"petty, nit-picky",ID:145},
    {German:"klug",English:"smart, clever",ID:146},
    {German:"komisch",English:"funny, comical, odd",ID:147},
    {German:"kompliziert",English:"complicated",ID:148},
    {German:"konservativ",English:"conservative",ID:149},
    {German:"kontaktfreudig",English:"sociable, outgoing",ID:150},
    {German:"kraeftig",English:"strong",ID:151},
    {German:"krank",English:"sick",ID:152},
    {German:"kreativ",English:"creative",ID:153},
    {German:"kritisch",English:"critical",ID:154},
    {German:"krumm",English:"crooked, hunched, bent",ID:155},
    {German:"labil",English:"unstable, frail",ID:156},
    {German:"lang",English:"long",ID:157},
    {German:"langsam",English:"slow",ID:158},
    {German:"langweilig",English:"boring",ID:159},
    {German:"launisch",English:"moody, temperamental",ID:160},
    {German:"laut",English:"loud, rowdy",ID:161},
    {German:"lebendig",English:"alive, lively",ID:162},
    {German:"leicht",English:"light, easy",ID:163},
    {German:"leidenschaftlich",English:"passionate",ID:164},
    {German:"leise",English:"quiet, soft",ID:165},
    {German:"letzte",English:"last",ID:166},
    {German:"lieb",English:"dear, beloved",ID:167},
    {German:"liebenswuerdig",English:"lovable, amiable",ID:168},
    {German:"lustig",English:"funny",ID:169},
    {German:"merkwuerdig",English:"unusual, strange",ID:170},
    {German:"misstrauisch",English:"mistrustful, distrustful",ID:171},
    {German:"modisch",English:"fashionable, stylish",ID:172},
    {German:"mollig",English:"plump, chubby",ID:173},
    {German:"moeglich",English:"possible",ID:174},
    {German:"moralisch",English:"moral, ethical",ID:175},
    {German:"mutig",English:"brave",ID:176},
    {German:"naechste",English:"next",ID:177},
    {German:"nachlaessig",English:"careless, negligent",ID:178},
    {German:"nah",English:"near",ID:179},
    {German:"naß",English:"wet",ID:180},
    {German:"neidisch",English:"envious",ID:181},
    {German:"nervoes",English:"nervous",ID:182},
    {German:"nett",English:"kind, nice (person)",ID:183},
    {German:"neu",English:"new",ID:184},
    {German:"neugierig",English:"curious",ID:185},
    {German:"niedergeschlagen",English:"depressed, dejected",ID:186},
    {German:"niedlich",English:"cute",ID:187},
    {German:"niedrig",English:"low",ID:188},
    {German:"notwendig",English:"necessary",ID:189},
    {German:"oberflaechlich",English:"superficial, shallow",ID:190},
    {German:"offen",English:"open",ID:191},
    {German:"oeffentlich",English:"public",ID:192},
    {German:"optimistisch",English:"optimistic",ID:193},
    {German:"ordentlich",English:"orderly",ID:194},
    {German:"passiv",English:"passive",ID:195},
    {German:"parteiisch",English:"partial, biased, one-sided",ID:196},
    {German:"peinlich",English:"embarrassing",ID:197},
    {German:"pessimistisch",English:"pessimistic",ID:198},
    {German:"praktisch",English:"practical",ID:199},
    {German:"privat",English:"private",ID:200},
    {German:"puenktlich",English:"punctual, prompt",ID:201},
    {German:"radikal",English:"radical, revolutionary",ID:202},
    {German:"raffiniert",English:"refined, elegant",ID:203},
    {German:"rauh",English:"rough",ID:204},
    {German:"rebellisch",English:"rebellious",ID:205},
    {German:"rechthaberisch",English:"self-opinionated",ID:206},
    {German:"redlich",English:"honest",ID:207},
    {German:"reich",English:"rich",ID:208},
    {German:"reif",English:"mature",ID:209},
    {German:"rein",English:"pure, clean, clear",ID:210},
    {German:"religioes",English:"religious",ID:211},
    {German:"richtig",English:"correct, proper",ID:212},
    {German:"riesig",English:"huge",ID:213},
    {German:"romantisch",English:"romantic",ID:214},
    {German:"rot",English:"red",ID:215},
    {German:"ruecksichtslos",English:"ruthless, inconsiderate",ID:216},
    {German:"ruecksichtsvoll",English:"considerate",ID:217},
    {German:"ruhig",English:"calm",ID:218},
    {German:"sauber",English:"clean",ID:219},
    {German:"sauer",English:"angry, sour",ID:220},
    {German:"schick",English:"chic, stylish, fancy",ID:221},
    {German:"schlampig",English:"messy, sloppy",ID:222},
    {German:"schlau",English:"clever, cunning",ID:223},
    {German:"schlecht",English:"bad, awful",ID:224},
    {German:"schmutzig",English:"dirty, filthy, soiled",ID:225},
    {German:"schnell",English:"fast, quick",ID:226},
    {German:"schoen",English:"beautiful, pretty, nice",ID:227},
    {German:"schuechtern",English:"shy",ID:228},
    {German:"schwach",English:"weak, frail",ID:229},
    {German:"schwarz",English:"black",ID:230},
    {German:"schwer, schwierig",English:"difficult, heavy",ID:231},
    {German:"schwerfaellig",English:"cumbersome, heavy, sluggish",ID:232},
    {German:"schwermuetig",English:"gloomy, melancholic",ID:233},
    {German:"selbstlos",English:"unselfish",ID:234},
    {German:"selbstsicher",English:"self-confident",ID:235},
    {German:"selbstsuechtig",English:"selfish",ID:236},
    {German:"selten",English:"rare",ID:237},
    {German:"seltsam",English:"strange, weird",ID:238},
    {German:"sensationell",English:"sensational",ID:239},
    {German:"sensibel",English:"sensitive",ID:240},
    {German:"sicher",English:"safe, secure, certainly",ID:241},
    {German:"sorgenlos, sorgenfrei",English:"carefree",ID:242},
    {German:"sorgfaeltig",English:"careful",ID:243},
    {German:"spaet",English:"late",ID:244},
    {German:"spontan",English:"spontaneous",ID:245},
    {German:"sportlich",English:"athletic",ID:246},
    {German:"spoettisch",English:"mocking, scornful",ID:247},
    {German:"staendig",English:"constant",ID:248},
    {German:"stark",English:"strong, powerful",ID:249},
    {German:"stolz (auf)",English:"proud (of)",ID:250},
    {German:"schlimm",English:"bad, awful",ID:251},]

 export {germanAdjective}
 const alphabet = [
    { letter: 'A' },
    { letter: 'B' },
    { letter: 'C' },
    { letter: 'D' },
    { letter: 'E' },
    { letter: 'F' },
    { letter: 'G' },
    { letter: 'H' },
    { letter: 'I' },
    { letter: 'J' },
    { letter: 'K' },
    { letter: 'L' },
    { letter: 'M' },
    { letter: 'N' },
    { letter: 'O' },
    { letter: 'P' },
    { letter: 'Q' },
    { letter: 'R' },
    { letter: 'S' },
    { letter: 'T' },
    { letter: 'U' },
    { letter: 'V' },
    { letter: 'W' },
    { letter: 'X' },
    { letter: 'Y' },
    { letter: 'Z' }
  ];
export {alphabet}